2025-05-04 03:35:29,164 [INFO] Starting mateIn3 puzzle solver training
2025-05-04 03:35:29,164 [INFO] Configuration: TrainingConfig(board_feature_dim=860, move_feature_dim=16, batch_size=32, policy_lr=0.0003, value_lr=0.0003, clip_epsilon=0.2, value_loss_coef=0.5, entropy_coef=0.01, ppo_epochs=4, gamma=0.99, lambda_gae=0.95, stockfish_path='/usr/games/stockfish', stockfish_depth=10, num_epochs=10, save_frequency=2, log_frequency=10, eval_frequency=1, train_split=0.8, val_split=0.1, test_split=0.1, replay_buffer_capacity=100000, min_buffer_size=1000, correct_move_bonus=1.0, stockfish_weight=0.5, mate_bonus=2.0, device='cuda', num_workers=4, data_dir='data', model_dir='models', log_dir='logs')
2025-05-04 03:35:29,164 [INFO] Loading puzzle dataset from lichess_db_puzzle.csv
2025-05-04 03:35:29,165 [ERROR] Training failed with error: [Errno 2] No such file or directory: 'lichess_db_puzzle.csv'
Traceback (most recent call last):
  File "scripts/train_matein3.py", line 127, in main
    train_puzzles, val_puzzles, test_puzzles = load_puzzle_dataset(args.data, config)
  File "scripts/train_matein3.py", line 50, in load_puzzle_dataset
    df = pd.read_csv(csv_path)
  File "/home/harish/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/harish/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/harish/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/harish/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/harish/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'lichess_db_puzzle.csv'
